version: 2.1
jobs:
  build:
    docker:
      - image: cimg/deploy:2022.11
    working_directory: ~/wkd
    steps:
      - checkout
      - run:
          name: Build
          command: 'rm -rf ./build && mkdir ./build && rsync -az --exclude-from=.distignore ./ ./build'
      - add_ssh_keys:
          fingerprints:
            - "$FINGERPRINT"
      - run:
          name: SSH
          command: 'ssh -o StrictHostKeyChecking=no $ENV_URL exit'
      - run:
          name: Deploy
          command: 'cd ./build && rsync -avz --delete . $ENV_URL:$ENV_FOLDER'
    resource_class: large
workflows:
  version: 2
  deploy:
    jobs:
      - build
